### PR TITLE
Rebuild for 0.8.14.

### PR DESCRIPTION
**Pull request by rhelgeby**
####  Description

Rebuild support/0.x so that the merge of pull request #906 is included in the build.

Even though it may not be ready for release, this allows other people to reference and test the support/0.x branch directly, using GitHub references in NPM's package.json.

####  Fixes Related issues
- Related to issue #903 with a bugfix for IE.

####  Checklist
- [X] I have read and understand the CONTRIBUTIONS.md file
- [X] I have searched for and linked related issues
- [ ] I have created test cases to ensure quick resolution of the PR is easier
- [x] I am NOT targeting main branch
- [ ] I did NOT include the dist folder in my PR

@json-schema-form/angular-schema-form-lead

### CODE REVIEW

**Comment by rhelgeby** [comment]
The build fails with a version conflict on jQuery. This also happened in build 246465021.

I don't know if the support/0.x branch would build before, but when I built it I resolved it with jQuery. Maybe this resolution should be marked in bower.json?

**Comment by Anthropic** [comment]
Thanks @rhelgeby let me know after a little while if you think it is stable enough for a release :)

**Comment by iCodr8** [comment]
What about a release?

**Comment by rhelgeby** [comment]
We use this version in production already and I suppose it's considered stable now.

I've forked and built my own version and reference my branch for this pull request directly: "angular-schema-form": "github:rhelgeby/angular-schema-form#build"

Warning: You can reference my fork as a temporary workaround. But don't rely on me to keep this branch or fork forever. I won't give notices of changes. It's better to have an official release and package in the NPM repository.

**Comment by iCodr8** [comment]
I have tested it and it works wonderful! Thank you!

The only problem was the way to use it. I had to use this variant:

```
"angular-schema-form": "git@github.com:rhelgeby/angular-schema-form.git#build"
```

This version should be in this repository as version `0.8.14`.

**Comment by rhelgeby** [comment]
Great. Even though I use this in production, again, remember that you use my fork on your own risk. I can't guarantee anything. If you want to ensure stability you could fork my clone and reference your own repository.

@Anthropic Could you make an official release for 0.8.14 when time permits? It's best if we all switch to an official version.

**Comment by Anthropic** [comment]
@rhelgeby I will, yes, glad it works for you all I will get onto it shortly, I'm recovering from surgery so there's been a slight delay in me getting to things as I am heavily medicated during recovery.

**Comment by Anthropic** [comment]
@rhelgeby
https://github.com/json-schema-form/angular-schema-form/releases/tag/v0.8.14
NPM is updated to 0.8.14 also.

**Pull request merged**
