### PR TITLE
Fix form.key issues

### PR DESCRIPTION
**Pull request by mnzaki**
####  Description
Generate proper form keys for arrays of strings and arrays of objects, and add some tests for it.
This also depends on a fix in angular-schema-form-bootstrap, specifically removing the `sf-key-controller` from `fieldset.html`

####  Fixes Related issues
Issue #870 

####  Checklist
- [x] I have read and understand the CONTRIBUTIONS.md file
- [x] I have searched for and linked related issues
- [x] I have created test cases to ensure quick resolution of the PR is easier
- [x] I am NOT targeting main branch
- [x] I did NOT include the dist folder in my PR

@json-schema-form/angular-schema-form-lead

### CODE REVIEW

**Comment by mnzaki** [comment]
Note that tests will fail because this depends on json-schema-form/angular-schema-form-bootstrap#42

**Comment by Anthropic** [comment]
@mnzaki I added your bootstrap change and it is still failing on strings, is something else missing?
    ✔ should generate correct form keys for array of objects
    ✔ should generate correct form keys for array of objects with user specified form
    ✖ should generate correct form keys for array of strings

Oh and thanks for noticing the dupe of tests, they were previously breaking the loop so I had to split them out to update the loop logic and forgot to clean them up.

**Comment by mnzaki** [comment]
It needs to be built as the karma tests use the built file in `dist/`, and I did not include that in the PR as required. The "array of objects" tests pass as they do not need changes in angular-schema-form, they only require the bootstrap fix.

**Comment by mnzaki** [comment]
Also there's one more fix missing here, the issue that I explained in [this comment](https://github.com/json-schema-form/angular-schema-form/issues/870#issuecomment-297963137):
```
        scope.initialForm = Object.assign({}, sfSchema.lookup['f' + attrs.sfField]);
/*->*/  scope.form = sfSchema.lookup['f' + attrs.sfField];
```

I was hesitant about fixing this as well as it might introduce bugs in projects using ASF and depending on this unexpected side effect (ie, updating form object and getting things changed without broadcasting a redraw event). What do you think?

**Comment by Anthropic** [comment]
@mnzaki I did the build, that's why it started passing two of the three, it was failing all three originally :)

**Comment by mnzaki** [comment]
I don't really fully know how the tests are run on Travis. But on `formKeyFixes` branch the angular-schema-form build inside `dist` is not updated, if you make a clean checkout and run the tests they will fail, but if you `npm run build` the tests will pass.

**Comment by Anthropic** [comment]
@mnzaki travisci clones the whole repo, then apply and merge the pr before running the tests, you can see the output here https://travis-ci.org/json-schema-form/angular-schema-form/pull_requests I believe that's visible to anyone. You can see that after I committed the re-built dist folder the test result changed, objects and strings failed in the last run but then only strings the next time. I had a quick look last night, but I need more time tonight to hopefully fix the strings, seems like there just a duplication of the key I need to eliminate.

**Comment by mnzaki** [comment]
@Anthropic yes and then it runs the tests through `npm run test` which uses `dist/angular-schema-form.js` (not from `src/`) so it needs to be built and committed as I did just now, then tests pass.

**Comment by Anthropic** [comment]
@mnzaki ah d'oh sorry was in too much of a rush to notice, I really should update the tests to run a build into a folder ignored by git... one day... thanks for taking the time to make sense for me! :)

I will try to look at your other suggestion shortly.

**Comment by mnzaki** [comment]
@Anthropic btw I think just changing the npm test script to `"webpack && karma start karma.conf.js --log-level debug --single-run"` would be enough to run the travis tests properly.

**Comment by Anthropic** [comment]
@mnzaki cheers, updated locally, will push on the weekend :)

**Pull request merged**
