### PR TITLE
Jeton's interpolation provider

### PR DESCRIPTION
**Pull request by jeton**
Relating to my previously stated issue (https://github.com/Textalk/angular-schema-form/issues/115) I have edited the template files, removing all references to hardcoded interpolation markup. I have also create a directive to be able to set a type and placeholder attrs of an input field without the need to for interpolation markup (default.html).

### CODE REVIEW

**Comment by dmi3000** [comment]
What ever happened to this code? I can't seem to pull down any version that contains it.

**Comment by davidlgj** [comment]
No it did not. Basically it's not the right solution either, not using expressions cripples us alot. And will be hard to enforce on third party add-ons. Especially when moving to bind once variants found in Angular 1.3. 

A better solution is to search and replace {{}} in the templates with something else and use the $interpolatipnProvider

**Comment by zwiy** [comment]
Is there any new solution for this problem/issue? Or is it better to search and replace?

**Comment by Anthropic** [comment]
@zwiy not aware of any other options sorry.

**Comment by vishnucr** [comment]
how can i replace {{ }} interpolation

**Pull request merged**
