### PR TITLE
#295 array on change

### PR DESCRIPTION
**Pull request by luciformed**
fix for #295, also #208 ? by calling ngModel.$setViewValue with a copy of array

### CODE REVIEW

**Comment by davidlgj** [comment]
Hi @luciformed, sorry for the late reply and thanks for the PR!

I'm a bit worried about the `angular.copy`, especially if the array items part of the form is large and complex. I'm gonna try it out :-)

**Comment by luciformed** [comment]
angular documentation is where I read you should pass copies to `$setViewValue`, i understand your concern with performance though.

**Comment by luciformed** [comment]
dod you get the chance to give it a try?

**Comment by davidlgj** [comment]
Sorry it's taking so long. I hope to get time to dig into this on friday.

**Comment by davidlgj** [comment]
I see that you set the view value to trigger a the `ngModel.$viewChangeListeners` that `sf-changed` use.  

I'm thinking it could be simpler to just call the onChange listener instead, that is. Something like the code here: https://github.com/Textalk/angular-schema-form/blob/development/src/directives/changed.js#L19

By the way, would you mind removing the `dist/` folder and its files from PR?

**Comment by oatkiller** [comment]
Any progress with this? I need type: array and I'm adding custom validation errors representing backend errors. This is killing me :(

**Comment by grjones** [comment]
I would love for this to be merged in.  It fixed our problems. :+1:

**Comment by luciformed** [comment]
sorry I forgot this was still hanging, I'll update the PR and hopefully it gets merged

**Comment by Anthropic** [comment]
@luciformed thanks for the PR, I've started maintaining the repo and starting to try and get on top of neglected PRs, could you do me a favour and **remove the dist folder** from the PR please?

**Comment by mmgm** [comment]
I was just about to submit an almost identical pull request (frankly with less tests, so this one is better) that solved our problem.

From my understanding this needs to also come with a pull request to angular-schema-form-bootstrap that removes sf-changed from https://github.com/json-schema-form/angular-schema-form-bootstrap/blob/develop/src/checkboxes.html

Is this correct? Is there anything I can do to help this get merged? @Anthropic

**Comment by Anthropic** [comment]
@mmgm @luciformed needs to remove the dist folder from the PR, ideally the changes would now be done against the webpack/babel branch too as that is soon to be merged into the main develop branch. But I need to write some documentation on how to work with that before then.

If you could pull @luciformed 's version to your own fork and then make a PR minus dist folder I could accept that if this one isn't updated.

**Comment by nicklasb** [comment]
@mmgm @luciformed, have you considered the proposal from @Anthropic?

**Comment by Anthropic** [comment]
I added your test case @luciformed and it now passes in the new version, thanks so much for making the test case :)

**Pull request closed without merging**
