### PR TITLE
form '*' generate only remain keys from schema

### PR DESCRIPTION
**Pull request by illiano**
#### Description

Add your description here
#### Fixes Related issues
- add related
- issues here
#### Checklist
- [x] I have read and understand the CONTRIBUTIONS.md file
- [x] I have searched for and linked related issues
- [ ] I have created test cases to ensure quick resolution of the PR is easier
- [x] I am NOT targeting main branch
- [x] I did NOT include the dist folder in my PR

@json-schema-form/angular-schema-form-lead
- it is now possible to add custom keys to the form and add '...' for the remaining keys

### CODE REVIEW

**Comment by Anthropic** [comment]
@illiano thanks for taking the time to make a PR I really appreciate it!
I was wondering if perhaps '...' may be a better identifier for 'rest' so the * can remain as it is, would that be a hard change to make to your PR?

**Comment by Anthropic** [comment]
@illiano thanks for the update, there's two things now that would get this merged quicker:

1) documentation update, I would have to find time to update the documentation before merging, if you can help with that I'd appreciate it, just needs to spell out behaviour so a user knows that it will only add fields not already added at the order position of where the '...' is added (assuming that's what it does?)

2) if you could make a plunker to show it in action?
Without a test case it would be nice to be able to ensure it is stable without having to do that myself, would really appreciate your time if you can help with that :)

Otherwise I will do my best to get this merged soon :)

**Comment by illiano** [comment]
I have created a plunker, where you can see the changes in action. 

https://plnkr.co/edit/7Oqxxl?p=preview

I think it's better, when you update the documentation :-)

**Comment by Anthropic** [comment]
@illiano I'm not sure the plunker is working, I changed the form to be:
```
  $scope.form = [
    "name",
    "...",
    "comment"
  ];
```
And the form renders 
"name",
"name",
"email",
"comment",
"comment"

Which is the same output as just using "*", is something missing?

**Comment by illiano** [comment]
i have fixed the bug.

**Comment by Anthropic** [comment]
Great, thank you very much @illiano I will merge once I make the same changes to the webpack branch hopefully I will have time tonight, then I will look at adding documentation for it.

**Comment by Anthropic** [comment]
@illiano this is in the alpha :)

**Pull request closed without merging**
