### PR TITLE
Fixed angular element children selector usage

### PR DESCRIPTION
**Pull request by apinnecke**
In jqLite, `.children()` selector is not able to take an selector argument. Caused by this error, the directive is removing all children, if no full jQuery is used.

### CODE REVIEW

**Comment by apinnecke** [comment]
Broken tests also broken in develop. ;)

**Comment by Anthropic** [comment]
@apinnecke thank you for the PR, I'm fairly new to managing the project and we are slowly starting to ramp back up and reviewing some neglected PRs, is there any chance you could write a test script for the change? It would be a huge help :)

**Comment by apinnecke** [comment]
Unfortunately I'm very much out of time these days. Ya, probably could write some tests, but can't tell when that will be. Plus: This change is already covered by the original tests AFAIK, so maybe these are enough? Has to be verified indeed.

**Comment by nicklasb** [comment]
@apinnecke Do you have some time to give some love to this PR?

**Comment by Anthropic** [comment]
@apinnecke thank you for the PR I finally got to it, I can't merge due to the number of changes since but I added the change to sf-schema.directive.js so thank you again for your help.

**Pull request closed without merging**
